
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MvcXmlEntities : DbContext
{
    public MvcXmlEntities()
        : base("name=MvcXmlEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ABDBulletin> ABDBulletin { get; set; }
    public DbSet<BIST100Bulletin> BIST100Bulletin { get; set; }
    public DbSet<ABDBulletinHistory> ABDBulletinHistory { get; set; }
    public DbSet<ABDCompanyCard> ABDCompanyCard { get; set; }
    public DbSet<ABDCompanyCardHistory> ABDCompanyCardHistory { get; set; }
    public DbSet<ABDStockAnalysis> ABDStockAnalysis { get; set; }
    public DbSet<ABDStockAnalysisHistory> ABDStockAnalysisHistory { get; set; }
    public DbSet<ABDViopAnalysis> ABDViopAnalysis { get; set; }
    public DbSet<ABDViopAnalysisHistory> ABDViopAnalysisHistory { get; set; }
    public DbSet<AccountForm> AccountForm { get; set; }
    public DbSet<ActivityReport> ActivityReport { get; set; }
    public DbSet<ActivityReportHistory> ActivityReportHistory { get; set; }
    public DbSet<Admin> Admin { get; set; }
    public DbSet<AdminAuthorization> AdminAuthorization { get; set; }
    public DbSet<AdminMenu> AdminMenu { get; set; }
    public DbSet<Bank> Bank { get; set; }
    public DbSet<BankAccount> BankAccount { get; set; }
    public DbSet<BankAccountHistory> BankAccountHistory { get; set; }
    public DbSet<BankHistory> BankHistory { get; set; }
    public DbSet<Banner> Banner { get; set; }
    public DbSet<BannerHistory> BannerHistory { get; set; }
    public DbSet<BIST100BulletinHistory> BIST100BulletinHistory { get; set; }
    public DbSet<BIST100CompanyCard> BIST100CompanyCard { get; set; }
    public DbSet<BIST100CompanyCardHistory> BIST100CompanyCardHistory { get; set; }
    public DbSet<BIST100StockAnalysis> BIST100StockAnalysis { get; set; }
    public DbSet<BIST100StockAnalysisHistory> BIST100StockAnalysisHistory { get; set; }
    public DbSet<BoardOfDirectors> BoardOfDirectors { get; set; }
    public DbSet<BoardOfDirectorsHistory> BoardOfDirectorsHistory { get; set; }
    public DbSet<Branch> Branch { get; set; }
    public DbSet<BranchHistory> BranchHistory { get; set; }
    public DbSet<City> City { get; set; }
    public DbSet<ComplainForm> ComplainForm { get; set; }
    public DbSet<ContactForm> ContactForm { get; set; }
    public DbSet<Country> Country { get; set; }
    public DbSet<District> District { get; set; }
    public DbSet<DocumentGalery> DocumentGalery { get; set; }
    public DbSet<DocumentGaleryFile> DocumentGaleryFile { get; set; }
    public DbSet<EmailList> EmailList { get; set; }
    public DbSet<Events> Events { get; set; }
    public DbSet<EventsHistory> EventsHistory { get; set; }
    public DbSet<ExpiredAccount> ExpiredAccount { get; set; }
    public DbSet<ExpiredAccountHistory> ExpiredAccountHistory { get; set; }
    public DbSet<ExportDocument> ExportDocument { get; set; }
    public DbSet<ExportDocumentHistory> ExportDocumentHistory { get; set; }
    public DbSet<FAQ> FAQ { get; set; }
    public DbSet<FAQCategory> FAQCategory { get; set; }
    public DbSet<FAQCategoryHistory> FAQCategoryHistory { get; set; }
    public DbSet<FAQHistory> FAQHistory { get; set; }
    public DbSet<FinancialStatement> FinancialStatement { get; set; }
    public DbSet<FinancialStatementHistory> FinancialStatementHistory { get; set; }
    public DbSet<ForeignTechnicalAnalysis> ForeignTechnicalAnalysis { get; set; }
    public DbSet<ForeignTechnicalAnalysisHistory> ForeignTechnicalAnalysisHistory { get; set; }
    public DbSet<Form> Form { get; set; }
    public DbSet<FormMailRelation> FormMailRelation { get; set; }
    public DbSet<GlobalBranch> GlobalBranch { get; set; }
    public DbSet<GlobalBranchHistory> GlobalBranchHistory { get; set; }
    public DbSet<JobApplicationForm> JobApplicationForm { get; set; }
    public DbSet<LanguageWord> LanguageWord { get; set; }
    public DbSet<LanguageWordValue> LanguageWordValue { get; set; }
    public DbSet<LanguageWordValueHistory> LanguageWordValueHistory { get; set; }
    public DbSet<LocalTechnicalAnalysis> LocalTechnicalAnalysis { get; set; }
    public DbSet<LocalTechnicalAnalysisHistory> LocalTechnicalAnalysisHistory { get; set; }
    public DbSet<MailAccount> MailAccount { get; set; }
    public DbSet<MailGroup> MailGroup { get; set; }
    public DbSet<MailGroupHistory> MailGroupHistory { get; set; }
    public DbSet<MainPageApplicationArea> MainPageApplicationArea { get; set; }
    public DbSet<MainPageApplicationAreaHistory> MainPageApplicationAreaHistory { get; set; }
    public DbSet<MainPageQuickMenu> MainPageQuickMenu { get; set; }
    public DbSet<MainPageQuickMenuHistory> MainPageQuickMenuHistory { get; set; }
    public DbSet<Module> Module { get; set; }
    public DbSet<News> News { get; set; }
    public DbSet<NewsletterForm> NewsletterForm { get; set; }
    public DbSet<OfficialAnnouncement> OfficialAnnouncement { get; set; }
    public DbSet<OfficialAnnouncementCategory> OfficialAnnouncementCategory { get; set; }
    public DbSet<OfficialAnnouncementCategoryHistory> OfficialAnnouncementCategoryHistory { get; set; }
    public DbSet<OfficialAnnouncementHistory> OfficialAnnouncementHistory { get; set; }
    public DbSet<Pages> Pages { get; set; }
    public DbSet<PagesHistory> PagesHistory { get; set; }
    public DbSet<PasswordRequestForm> PasswordRequestForm { get; set; }
    public DbSet<PhotoGalery> PhotoGalery { get; set; }
    public DbSet<PhotoGaleryFile> PhotoGaleryFile { get; set; }
    public DbSet<PopUp> PopUp { get; set; }
    public DbSet<PressRelease> PressRelease { get; set; }
    public DbSet<PressReleaseCategory> PressReleaseCategory { get; set; }
    public DbSet<Prospectus> Prospectus { get; set; }
    public DbSet<ProspectusHistory> ProspectusHistory { get; set; }
    public DbSet<QualityDocument> QualityDocument { get; set; }
    public DbSet<Region> Region { get; set; }
    public DbSet<SeminarForm> SeminarForm { get; set; }
    public DbSet<Setting> Setting { get; set; }
    public DbSet<VideoGalery> VideoGalery { get; set; }
    public DbSet<VideoGaleryFile> VideoGaleryFile { get; set; }
    public DbSet<vwUrlList> vwUrlList { get; set; }
    public DbSet<OtherReportsHistory> OtherReportsHistory { get; set; }
    public DbSet<AskYourStockForm> AskYourStockForm { get; set; }
    public DbSet<CompanyReport> CompanyReport { get; set; }
    public DbSet<IndustryReport> IndustryReport { get; set; }
    public DbSet<ModelPortfolio> ModelPortfolio { get; set; }
    public DbSet<CompanyReportHistory> CompanyReportHistory { get; set; }
    public DbSet<IndustryReportHistory> IndustryReportHistory { get; set; }
    public DbSet<ModelPortfolioHistory> ModelPortfolioHistory { get; set; }
    public DbSet<OtherReports> OtherReports { get; set; }
    public DbSet<NovemberEventMember> NovemberEventMember { get; set; }
}
