//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ABDBulletin
{
    public int ABDBulletinID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ABDBulletinHistory
{
    public int ABDBulletinHistoryID { get; set; }
    public int ABDBulletinID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class ABDCompanyCard
{
    public int ABDCompanyCardID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ABDCompanyCardHistory
{
    public int ABDCompanyCardHistoryID { get; set; }
    public int ABDCompanyCardID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class ABDStockAnalysis
{
    public int ABDStockAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ABDStockAnalysisHistory
{
    public int ABDStockAnalysisHistoryID { get; set; }
    public int ABDStockAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class ABDViopAnalysis
{
    public int ABDViopAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ABDViopAnalysisHistory
{
    public int ABDViopAnalysisHistoryID { get; set; }
    public int ABDViopAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class AccountForm
{
    public int AccountFormID { get; set; }
    public string NameSurname { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public bool KVKK { get; set; }
    public bool AcceptElectronicMessage { get; set; }
    public System.DateTime AddDate { get; set; }
    public string IpAddress { get; set; }
    public int LangID { get; set; }
}

public partial class ActivityReport
{
    public int ActivityReportID { get; set; }
    public int Year { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class ActivityReportHistory
{
    public int ActivityReportHistoryID { get; set; }
    public int ActivityReportID { get; set; }
    public int Year { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public string Title { get; set; }
}

public partial class Admin
{
    public int AdminID { get; set; }
    public string UserName { get; set; }
    public string PassWord { get; set; }
    public string Email { get; set; }
    public bool UserAuth { get; set; }
    public bool Status { get; set; }
}

public partial class AdminAuthorization
{
    public int AdminAuthorizationID { get; set; }
    public int AdminID { get; set; }
    public int AdminMenuID { get; set; }
    public bool Allow { get; set; }
}

public partial class AdminMenu
{
    public int AdminMenuID { get; set; }
    public Nullable<int> ParentID { get; set; }
    public string Title { get; set; }
    public string Url { get; set; }
    public int Line { get; set; }
    public bool AllowAuth { get; set; }
    public Nullable<byte> PageType { get; set; }
    public bool ShowInSubMenu { get; set; }
}

public partial class AskYourStockForm
{
    public int AskYourStockFormID { get; set; }
    public string NameSurname { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string StockCode { get; set; }
    public string AccountNo { get; set; }
    public string UtmID { get; set; }
    public string UtmMedium { get; set; }
    public string UtmCampaign { get; set; }
    public string UtmSource { get; set; }
    public string GclID { get; set; }
    public bool KVKK { get; set; }
    public bool AcceptElectronicMessage { get; set; }
    public System.DateTime AddDate { get; set; }
    public string IpAddress { get; set; }
    public int LangID { get; set; }
}

public partial class Bank
{
    public int BankID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class BankAccount
{
    public int BankAccountID { get; set; }
    public int BankID { get; set; }
    public string Title { get; set; }
    public string Iban { get; set; }
    public string Unit { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public int Line { get; set; }
}

public partial class BankAccountHistory
{
    public int BankAccountHistoryID { get; set; }
    public int BankAccountID { get; set; }
    public int BankID { get; set; }
    public string Title { get; set; }
    public string Iban { get; set; }
    public string Unit { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public int Line { get; set; }
}

public partial class BankHistory
{
    public int BankHistoryID { get; set; }
    public int BankID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class Banner
{
    public int BannerID { get; set; }
    public string RedirectTitle { get; set; }
    public string ImageUrl { get; set; }
    public int PageID { get; set; }
    public string Url { get; set; }
    public string Target { get; set; }
    public string YoutubeVideoCode { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public string Body { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class BannerHistory
{
    public int BannerHistoryID { get; set; }
    public int BannerID { get; set; }
    public string RedirectTitle { get; set; }
    public string ImageUrl { get; set; }
    public int PageID { get; set; }
    public string Url { get; set; }
    public string Target { get; set; }
    public string YoutubeVideoCode { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public string Body { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class BIST100Bulletin
{
    public int BIST100BulletinID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class BIST100BulletinHistory
{
    public int BIST100BulletinHistoryID { get; set; }
    public int BIST100BulletinID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class BIST100CompanyCard
{
    public int BIST100CompanyCardID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class BIST100CompanyCardHistory
{
    public int BIST100CompanyCardHistoryID { get; set; }
    public int BIST100CompanyCardID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class BIST100StockAnalysis
{
    public int BIST100StockAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class BIST100StockAnalysisHistory
{
    public int BIST100StockAnalysisHistoryID { get; set; }
    public int BIST100StockAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class BoardOfDirectors
{
    public int BoardOfDirectorsID { get; set; }
    public string NameSurname { get; set; }
    public string Degree { get; set; }
    public int DirectorType { get; set; }
    public string Linkedin { get; set; }
    public string ImageUrl { get; set; }
    public int Line { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class BoardOfDirectorsHistory
{
    public int BoardOfDirectorsHistoryID { get; set; }
    public int BoardOfDirectorsID { get; set; }
    public string NameSurname { get; set; }
    public string Degree { get; set; }
    public int DirectorType { get; set; }
    public string Linkedin { get; set; }
    public string ImageUrl { get; set; }
    public int Line { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public string Title { get; set; }
}

public partial class Branch
{
    public int BranchID { get; set; }
    public string Title { get; set; }
    public string Address { get; set; }
    public int CityID { get; set; }
    public string Fax { get; set; }
    public string Phone { get; set; }
    public string Coordinate { get; set; }
    public string MapSource { get; set; }
    public int Line { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class BranchHistory
{
    public int BranchHistoryID { get; set; }
    public int BranchID { get; set; }
    public string Title { get; set; }
    public string Address { get; set; }
    public int CityID { get; set; }
    public string Fax { get; set; }
    public string Phone { get; set; }
    public string Coordinate { get; set; }
    public string MapSource { get; set; }
    public int Line { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class City
{
    public int CityID { get; set; }
    public string CityName { get; set; }
}

public partial class CompanyReport
{
    public int CompanyReportID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class CompanyReportHistory
{
    public int CompanyReportHistoryID { get; set; }
    public int CompanyReportID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class ComplainForm
{
    public int ComplainFormID { get; set; }
    public string NameSurname { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string AccountNumber { get; set; }
    public string Address { get; set; }
    public string PersonType { get; set; }
    public string Subject { get; set; }
    public string Message { get; set; }
    public bool KVKK { get; set; }
    public bool AcceptElectronicMessage { get; set; }
    public System.DateTime AddDate { get; set; }
    public string IpAddress { get; set; }
    public int LangID { get; set; }
}

public partial class ContactForm
{
    public int ContactFormID { get; set; }
    public string NameSurname { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Message { get; set; }
    public bool KVKK { get; set; }
    public bool AcceptElectronicMessage { get; set; }
    public System.DateTime AddDate { get; set; }
    public string IpAddress { get; set; }
    public int LangID { get; set; }
}

public partial class Country
{
    public int CountryID { get; set; }
    public string Country_Name { get; set; }
}

public partial class District
{
    public int DistrictID { get; set; }
    public string DistrictName { get; set; }
    public int CityID { get; set; }
}

public partial class DocumentGalery
{
    public int DocumentGaleryID { get; set; }
    public int DocumentGaleryParentID { get; set; }
    public string Name { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
}

public partial class DocumentGaleryFile
{
    public int DocumentGaleryFileID { get; set; }
    public int DocumentGaleryID { get; set; }
    public string DocumentGaleryFileDescription { get; set; }
    public string DocumentGaleryFileUrl { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
}

public partial class EmailList
{
    public int EmailListID { get; set; }
    public string Email { get; set; }
    public System.DateTime AddDate { get; set; }
    public string Adres { get; set; }
    public string cli_ip { get; set; }
    public string cli_dil { get; set; }
    public string iptal { get; set; }
}

public partial class Events
{
    public int EventsID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Contents { get; set; }
    public string LinkUrl { get; set; }
    public string RawUrl { get; set; }
    public int PhotoGaleryID { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class EventsHistory
{
    public int EventsHistoryID { get; set; }
    public int EventsID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Contents { get; set; }
    public int PhotoGaleryID { get; set; }
    public string LinkUrl { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public string RawUrl { get; set; }
}

public partial class ExpiredAccount
{
    public int ExpiredAccountID { get; set; }
    public string NameSurname { get; set; }
    public int MemberType { get; set; }
    public System.DateTime LastProcessDate { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class ExpiredAccountHistory
{
    public int ExpiredAccountHistoryID { get; set; }
    public int ExpiredAccountID { get; set; }
    public string NameSurname { get; set; }
    public int MemberType { get; set; }
    public System.DateTime LastProcessDate { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class ExportDocument
{
    public int ExportDocumentID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ExportDocumentHistory
{
    public int ExportDocumentHistoryID { get; set; }
    public int ExportDocumentID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class FAQ
{
    public int FAQID { get; set; }
    public int FAQCategoryID { get; set; }
    public string Question { get; set; }
    public string Answer { get; set; }
    public bool Status { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class FAQCategory
{
    public int FAQCategoryID { get; set; }
    public string Title { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class FAQCategoryHistory
{
    public int FAQCategoryHistoryID { get; set; }
    public int FAQCategoryID { get; set; }
    public string Title { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class FAQHistory
{
    public int FAQHistoryID { get; set; }
    public int FAQID { get; set; }
    public int FAQCategoryID { get; set; }
    public string Question { get; set; }
    public string Answer { get; set; }
    public bool Status { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class FinancialStatement
{
    public int FinancialStatementID { get; set; }
    public int Quarter { get; set; }
    public int Year { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class FinancialStatementHistory
{
    public int FinancialStatementHistoryID { get; set; }
    public int FinancialStatementID { get; set; }
    public int Quarter { get; set; }
    public int Year { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public string Title { get; set; }
}

public partial class ForeignTechnicalAnalysis
{
    public int ForeignTechnicalAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ForeignTechnicalAnalysisHistory
{
    public int ForeignTechnicalAnalysisHistoryID { get; set; }
    public int ForeignTechnicalAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class Form
{
    public int FormID { get; set; }
    public string FormName { get; set; }
    public string Module { get; set; }
    public string ClassName { get; set; }
    public string Header { get; set; }
    public string ListIndex { get; set; }
}

public partial class FormMailRelation
{
    public int FormMailRelationID { get; set; }
    public int FormID { get; set; }
    public int MailGroupID { get; set; }
}

public partial class GlobalBranch
{
    public int GlobalBranchID { get; set; }
    public string ShortContent { get; set; }
    public string Address { get; set; }
    public int CountryID { get; set; }
    public string Fax { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string Web { get; set; }
    public int Line { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class GlobalBranchHistory
{
    public int GlobalBranchHistoryID { get; set; }
    public int GlobalBranchID { get; set; }
    public string ShortContent { get; set; }
    public string Address { get; set; }
    public int CountryID { get; set; }
    public string Fax { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string Web { get; set; }
    public int Line { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public string Title { get; set; }
}

public partial class IndustryReport
{
    public int IndustryReportID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class IndustryReportHistory
{
    public int IndustryReportHistoryID { get; set; }
    public int IndustryReportID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class JobApplicationForm
{
    public int JobApplicationFormID { get; set; }
    public string ApplicationType { get; set; }
    public string NameSurname { get; set; }
    public string Gender { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public int CityID { get; set; }
    public int DistrictID { get; set; }
    public string SPKLicenseLevel { get; set; }
    public string UniversityName { get; set; }
    public string FacultyName { get; set; }
    public string HighSchoolName { get; set; }
    public string LastCompanyName { get; set; }
    public string LastWorkMission { get; set; }
    public string LastWorkDegree { get; set; }
    public Nullable<System.DateTime> LastWorkStartDate { get; set; }
    public Nullable<System.DateTime> LastWorkStopDate { get; set; }
    public bool LastWorkStill { get; set; }
    public string PreviousCompanyName { get; set; }
    public string PreviousWorkMission { get; set; }
    public string PreviousWorkDegree { get; set; }
    public Nullable<System.DateTime> PreviousWorkStartDate { get; set; }
    public Nullable<System.DateTime> PreviousWorkStopDate { get; set; }
    public int PreferCityID1 { get; set; }
    public int PreferCityID2 { get; set; }
    public int PreferCityID3 { get; set; }
    public string Resume { get; set; }
    public string FileUrl { get; set; }
    public int LangID { get; set; }
    public System.DateTime AddDate { get; set; }
    public bool KVKK { get; set; }
    public bool AcceptElectronicMessage { get; set; }
}

public partial class LanguageWord
{
    public int LanguageWordID { get; set; }
    public string Word { get; set; }
}

public partial class LanguageWordValue
{
    public int LanguageWordValueID { get; set; }
    public int LanguageWordID { get; set; }
    public string Value { get; set; }
    public int Lang { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class LanguageWordValueHistory
{
    public int LanguageWordValueHistoryID { get; set; }
    public int LanguageWordValueID { get; set; }
    public int LanguageWordID { get; set; }
    public string Value { get; set; }
    public int Lang { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class LocalTechnicalAnalysis
{
    public int LocalTechnicalAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class LocalTechnicalAnalysisHistory
{
    public int LocalTechnicalAnalysisHistoryID { get; set; }
    public int LocalTechnicalAnalysisID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class MailAccount
{
    public int MailAccountID { get; set; }
    public int MailGroupID { get; set; }
    public string DisplayName { get; set; }
    public string Address { get; set; }
}

public partial class MailGroup
{
    public int MailGroupID { get; set; }
    public string MailGroupName { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
}

public partial class MailGroupHistory
{
    public int MailGroupHistoryID { get; set; }
    public int MailGroupID { get; set; }
    public string MailGroupName { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public string Title { get; set; }
}

public partial class MainPageApplicationArea
{
    public int MainPageApplicationAreaID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string BoxType { get; set; }
    public string PdfUrl { get; set; }
    public string ImageUrl { get; set; }
    public string PlayStoreUrl { get; set; }
    public string AppleStoreUrl { get; set; }
    public string WindowsUrl { get; set; }
    public string Url { get; set; }
    public string Target { get; set; }
    public int PageID { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class MainPageApplicationAreaHistory
{
    public int MainPageApplicationAreaHistoryID { get; set; }
    public int MainPageApplicationAreaID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string BoxType { get; set; }
    public string PdfUrl { get; set; }
    public string ImageUrl { get; set; }
    public string PlayStoreUrl { get; set; }
    public string AppleStoreUrl { get; set; }
    public string WindowsUrl { get; set; }
    public string Url { get; set; }
    public string Target { get; set; }
    public int PageID { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class MainPageQuickMenu
{
    public int MainPageQuickMenuID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public string Url { get; set; }
    public string Target { get; set; }
    public int PageID { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class MainPageQuickMenuHistory
{
    public int MainPageQuickMenuHistoryID { get; set; }
    public int MainPageQuickMenuID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public string Url { get; set; }
    public string Target { get; set; }
    public int PageID { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class ModelPortfolio
{
    public int ModelPortfolioID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ModelPortfolioHistory
{
    public int ModelPortfolioHistoryID { get; set; }
    public int ModelPortfolioID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class Module
{
    public int ModuleID { get; set; }
    public string ModuleName { get; set; }
    public string ModulePath { get; set; }
}

public partial class News
{
    public int NewsID { get; set; }
    public int PhotoGaleryID { get; set; }
    public string Title { get; set; }
    public string BriefDescription { get; set; }
    public string Body { get; set; }
    public string Description { get; set; }
    public string Keywords { get; set; }
    public string ImageUrl { get; set; }
    public string RawUrl { get; set; }
    public string LinkUrl { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
}

public partial class NewsletterForm
{
    public int NewsletterFormID { get; set; }
    public string Email { get; set; }
    public System.DateTime AddDate { get; set; }
    public string IpAddress { get; set; }
    public int LangID { get; set; }
}

public partial class NovemberEventMember
{
    public System.Guid Id { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Company { get; set; }
    public string Position { get; set; }
    public System.DateTime CreatedDate { get; set; }
}

public partial class OfficialAnnouncement
{
    public int OfficialAnnouncementID { get; set; }
    public int OfficialAnnouncementCategoryID { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class OfficialAnnouncementCategory
{
    public int OfficialAnnouncementCategoryID { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public string Title { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
}

public partial class OfficialAnnouncementCategoryHistory
{
    public int OfficialAnnouncementCategoryHistoryID { get; set; }
    public int OfficialAnnouncementCategoryID { get; set; }
    public string Title { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class OfficialAnnouncementHistory
{
    public int OfficialAnnouncementHistoryID { get; set; }
    public int OfficialAnnouncementID { get; set; }
    public int OfficialAnnouncementCategoryID { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class OtherReports
{
    public int OtherReportID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public Nullable<int> Lang { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
    public Nullable<int> CreatedId { get; set; }
    public Nullable<int> ModifiedId { get; set; }
}

public partial class OtherReportsHistory
{
    public int OtherReportHistoryID { get; set; }
    public int OtherReportID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public System.DateTime Date { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
}

public partial class Pages
{
    public int PageID { get; set; }
    public int ParentID { get; set; }
    public string DisplayName { get; set; }
    public string SubTitle { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Keywords { get; set; }
    public string ShortContent { get; set; }
    public string Body { get; set; }
    public string ImageUrl { get; set; }
    public string ExtarnalLink { get; set; }
    public string RawUrl { get; set; }
    public string LinkUrl { get; set; }
    public string ExternalUrl { get; set; }
    public int Menu { get; set; }
    public int ModuleID { get; set; }
    public int FormID { get; set; }
    public int FAQCatergoryID { get; set; }
    public string ControlParameter { get; set; }
    public bool ShowHeaderTopMenu { get; set; }
    public bool ShowHeaderMenu { get; set; }
    public bool ShowFooterMenu { get; set; }
    public bool HiddenSitemap { get; set; }
    public bool HiddenChildrenSitemap { get; set; }
    public int ShowInMenu { get; set; }
    public string PhotoGaleries { get; set; }
    public string VideoGaleries { get; set; }
    public string DocumentGaleries { get; set; }
    public string Target { get; set; }
    public string rel { get; set; }
    public bool Locked { get; set; }
    public bool ShowBoxModel { get; set; }
    public byte PageType { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class PagesHistory
{
    public int PageHistoryID { get; set; }
    public int PageID { get; set; }
    public int ParentID { get; set; }
    public string DisplayName { get; set; }
    public string SubTitle { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Keywords { get; set; }
    public string ShortContent { get; set; }
    public string Body { get; set; }
    public string ImageUrl { get; set; }
    public string ExtarnalLink { get; set; }
    public string RawUrl { get; set; }
    public string LinkUrl { get; set; }
    public string ExternalUrl { get; set; }
    public int Menu { get; set; }
    public int ModuleID { get; set; }
    public int FormID { get; set; }
    public int FAQCatergoryID { get; set; }
    public string ControlParameter { get; set; }
    public bool ShowHeaderTopMenu { get; set; }
    public bool ShowHeaderMenu { get; set; }
    public bool ShowFooterMenu { get; set; }
    public bool HiddenSitemap { get; set; }
    public bool HiddenChildrenSitemap { get; set; }
    public int ShowInMenu { get; set; }
    public string PhotoGaleries { get; set; }
    public string VideoGaleries { get; set; }
    public string DocumentGaleries { get; set; }
    public string Target { get; set; }
    public string rel { get; set; }
    public bool Locked { get; set; }
    public bool ShowBoxModel { get; set; }
    public byte PageType { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class PasswordRequestForm
{
    public int PasswordRequestFormID { get; set; }
    public string Email { get; set; }
    public string AccountNumber { get; set; }
    public bool KVKK { get; set; }
    public bool AcceptElectronicMessage { get; set; }
    public System.DateTime AddDate { get; set; }
    public int LangID { get; set; }
    public string IpAddress { get; set; }
}

public partial class PhotoGalery
{
    public int PhotoGaleryID { get; set; }
    public int PhotoGaleryParentID { get; set; }
    public string Name { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
}

public partial class PhotoGaleryFile
{
    public int PhotoGaleryFileID { get; set; }
    public int PhotoGaleryID { get; set; }
    public string PhotoGaleryFileDescription { get; set; }
    public string PhotoGaleryFileUrl { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
}

public partial class PopUp
{
    public int PopUpID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int PageID { get; set; }
    public string Url { get; set; }
    public string Target { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
}

public partial class PressRelease
{
    public int PressReleaseID { get; set; }
    public int PressReleaseCategoryID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
    public System.DateTime Date { get; set; }
}

public partial class PressReleaseCategory
{
    public int PressReleaseCategoryID { get; set; }
    public string Title { get; set; }
    public int Lang { get; set; }
    public bool Status { get; set; }
}

public partial class Prospectus
{
    public int ProspectusID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
}

public partial class ProspectusHistory
{
    public int ProspectusHistoryID { get; set; }
    public int ProspectusID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public System.DateTime Date { get; set; }
    public bool Status { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public int CreatedId { get; set; }
    public int ModifiedId { get; set; }
    public System.DateTime HistoryCreateDate { get; set; }
}

public partial class QualityDocument
{
    public int QualityDocumentID { get; set; }
    public string QualityDocumentName { get; set; }
    public string ImageUrl { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime AddDate { get; set; }
}

public partial class Region
{
    public int RegionID { get; set; }
    public string RegionName { get; set; }
    public int CityID { get; set; }
}

public partial class SeminarForm
{
    public int SeminarFormID { get; set; }
    public string NameSurname { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string UtmID { get; set; }
    public string UtmMedium { get; set; }
    public string UtmCampaign { get; set; }
    public string UtmSource { get; set; }
    public string GclID { get; set; }
    public bool KVKK { get; set; }
    public bool AcceptElectronicMessage { get; set; }
    public System.DateTime AddDate { get; set; }
    public string IpAddress { get; set; }
    public int LangID { get; set; }
}

public partial class Setting
{
    public int SettingID { get; set; }
    public Nullable<bool> Active { get; set; }
    public string PassiveContent { get; set; }
    public string SMTPName { get; set; }
    public string SMTPServer { get; set; }
    public string SMTPEmail { get; set; }
    public string SMTPPassword { get; set; }
    public Nullable<int> SMTPPort { get; set; }
    public string Pagetitle { get; set; }
    public string Sitedomain { get; set; }
    public string Imagedir { get; set; }
    public string Flashdir { get; set; }
    public string Documentdir { get; set; }
}

public partial class VideoGalery
{
    public int VideoGaleryID { get; set; }
    public int VideoGaleryParentID { get; set; }
    public string Name { get; set; }
    public int Lang { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
    public System.DateTime AddDate { get; set; }
}

public partial class VideoGaleryFile
{
    public int VideoGaleryFileID { get; set; }
    public int VideoGaleryID { get; set; }
    public string VideoGaleryFileDescription { get; set; }
    public string VideoGaleryEmbed { get; set; }
    public string VideoGaleryFileUrl { get; set; }
    public string VideoGaleryFilePath { get; set; }
    public string Pixel { get; set; }
    public string Kbyte { get; set; }
    public int VideoSize { get; set; }
    public int Line { get; set; }
    public bool Status { get; set; }
}

public partial class vwUrlList
{
    public int RowID { get; set; }
    public string SayfaTipi { get; set; }
    public string RawUrl { get; set; }
    public string LinkUrl { get; set; }
}
